# Generated by Django 5.2.18 on 2026-10-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Murshid Store', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('business_email', models.EmailField(default='admin@murshid.com', max_length=254)),
                ('business_phone', models.CharField(default='', max_length=20)),
                ('business_address', models.TextField(default='')),
                ('whatsapp_number', models.CharField(default='919876543210', help_text='Include country code, e.g. 919876543210', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
